---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: run gcc
      shell: gcc --version > gcc.version
      args:
        creates: gcc.version

    - name: run make
      shell: make --version > make.version
      args:
        creates: make.version
